package com.staticguard.enums;

public enum TypeContext {
    FIELD,
    LOCAL_VARIABLE,
    PARAMETER,
    RETURN_TYPE,
    GENERIC_ARGUMENT,
    ARRAY_COMPONENT,
    INSTANTIATION,
    CAST,
    THROWS,
    EXTENDS,
    CATCH, IMPLEMENTS,
    INSTANCEOF,
    CLASS_LITERAL,
    RECORD_COMPONENT,
    METHOD_GENERIC_ARGUMENT,
    GENERIC_BOUND,

    // Only C
    TYPEDEF,
    STRUCT, UNION,
    ENUM,
    GLOBAL_VARIABLE,
    POINTER,
    FUNCTION_POINTER,
    SIZEOF
}
