package com.staticguard.enums;

public enum TypeContext {
    FIELD,
    LOCAL_VARIABLE,
    PARAMETER,
    RETURN_TYPE,
    GENERIC_ARGUMENT,
    ARRAY_COMPONENT,
    INSTANTIATION,
    CAST,
    THROWS,
    EXTENDS,
    CATCH, IMPLEMENTS,
    RECORD_COMPONENT,

    // Only C
    TYPEDEF,
    STRUCT, UNION,
    ENUM,
    GLOBAL_VARIABLE,
    POINTER,
    FUNCTION_POINTER,
    SIZEOF,
    STATIC_METHOD_CALL,
    STATIC_FIELD_ACCESS
}
