package com.staticguard.enums;

public enum TypeContext {
    FIELD,
    LOCAL_VARIABLE,
    PARAMETER,
    RETURN_TYPE,
    GENERIC_ARGUMENT,
    ARRAY_COMPONENT,
    INSTANTIATION,
    CAST,
    THROWS,
    EXTENDS,
    CATCH, IMPLEMENTS,
    RECORD_COMPONENT,
    STATIC_METHOD_CALL,
    STATIC_FIELD_ACCESS,

    // Only C
    TYPEDEF,
    GLOBAL_VARIABLE,
}
